### ISSUE TITLE
born-dead repositories

### ISSUE THREAD

**Issue by frisi** [collective/collective.github.com#796]
seems there are a couple of repositories on collective github that never had any commits pushed online.

eg: https://github.com/collective/collective.excludefromnavigation/issues/1
or https://github.com/collective/collective.zipreader/issues/1

as @jakesyl suggested it would be great if there was a way to find such repositories and remove them after one year of inactivity.

is there a way to find out who created the repositories - so we can ask the authors/initiators if they just forgot to push their code to the public repository?

**Comment by aclark4life** [comment]
Yep, please open an issue to request removal of specific unused repositories. Thanks
