### ISSUE TITLE
Adding an issue tracker for repositories

### ISSUE THREAD

**Issue by davidjb** [collective/collective.github.com#823]
Can the GitHub issue tracker be enabled for the following:

https://github.com/collective/diazotheme.frameworks
and
https://github.com/collective/diazotheme.bootswatch

I'd like to have a location to log and discuss issues with these packages.  Unsure what rights I would get as a standard Collective member, but if I can have the ability to close tickets in these repos (when complete) that would be perfect.

Thanks.

**Comment by jensens** [comment]
done
