### ISSUE TITLE
plone.recipe.plone import into collective

### ISSUE THREAD

**Issue by avolkov** [collective/collective.github.com#825]
I imported two old plone repositories from svn into github that no longer seem to work properly -- plone.recipe.plone no longer successfully builds older versions of Plone (pre-3.2).

I want to get them fixed, although not sure if they belong to the collective or core Plone.

[plone.recipe.plone](https://github.com/avolkov/plone.recipe.plone) -- [svn](http://svn.plone.org/svn/plone/dist/plone.recipe.plone/)

[dist_plone](https://github.com/avolkov/dist_plone) -- [svn](https://svn.plone.org/svn/plone/Installers/dist_plone/)

**Comment by thet** [comment]
when importing from plone svn into github (which is VERY welcome), please follow the guideline here: https://github.com/collective/collective.github.com/blob/master/old-svn.rst
which is to keep author info, migrate all branches and tags, add "moved to github" info on orig svn repo....

**Comment by avolkov** [comment]
@thet  Thanks for the info! I have a few issues I'm having with the projects, they're mostly non technical, as I'm dealing with the older version of packages and not sure to what part of the project they are relevant.

These packages are in http://svn.plone.org/svn/plone/ although there are compelling reasons to move them to collective as these packages are pretty old, haven't been maintained since 2011  and mostly relevant to building legacy Plone 2.x and 3.x releases. The reason why I want to move this packages to github -- I need to set up a few older releases with buildout and hardcoded and when I try to install them from [pypi](https://pypi.python.org/pypi/plone.recipe.plone) links for many of the packages no longer work.
Should I raise the issue on with Plone project?

I already imported these repositories using git-svn preserving author info (I manuall looked up authors), however I converted tags to branches, I think with the layout of project -- every tag is a requirements reference for a particular version of Plone and I can recreate tags by hand. I can redo the work with svn2git but I checked the layout of other converted project and it looks similar.

I'm guess I need to get core Plone contrib privileges in order to proceed with this.

**Comment by jensens** [comment]
btw. https://import.github.com/new works usually well for me (even if it takes ages until its imported)

BUT since you already sucessfully imported everything into your account, the easiest is if I fork both into collective and afterwards you delete them from your account. Would that work for you?

**Comment by avolkov** [comment]
@jensens  Yes that would work for me. Thanks.

 Though I should eggify the main package and fix broken repository refs in dist_plone. Once everything is good to go I'll do as you suggested and move everything in the collective.

**Comment by aclark4life** [comment]
Is this done?
