### ISSUE TITLE
Enable Travis for collective.searchandreplace

### ISSUE THREAD

**Issue by mauritsvanrees** [collective/collective.github.com#829]
Can you enable the Travis hook for https://github.com/collective/collective.searchandreplace? Thanks.

**Comment by jensens** [comment]
enabled at github, but have problems to access https://travis-ci.org/profile/collective

**Comment by jensens** [comment]
worked now

**Comment by mauritsvanrees** [comment]
Thanks, it works. Badge added, also on PyPI.
