### ISSUE TITLE
A new Pythoner wanna have a research

### ISSUE THREAD

**Issue by batehurry** [collective/collective.github.com#832]
I'm a new Pythoner, found PLONE on GOOGLE and wanna have a excellent src to learn. Would you like give a ticket to me.

**Comment by vangheem** [comment]
Would you like access to the collective or want to work on a bug fix for the core product?

The collective is for shared plone add-on development.

**Comment by jensens** [comment]
For questions about Plone we have a great platform at https://community.plone.org/ - see you there!
