### ISSUE TITLE
Please add me to the collective

### ISSUE THREAD

**Issue by instification** [collective/collective.github.com#842]
Hi,

I have signed a contributors agreement (at the conference in Bristol). Could I get access to the collective as well please?

Thank you
Jon

**Comment by jcbrand** [comment]
You certainly may. Invite sent.

**Comment by djowett** [comment]
Welcome Jon!

On 22/06/15 11:33, Jon Pentland wrote:
>
> Hi,
>
> I have signed a contributors agreement (at the conference in Bristol). 
> Could I get access to the collective as well please?
>
> Thank you
> Jon
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/collective/collective.github.com/issues/842>.
>

-- 
Daniel Jowett

*Jowett Enterprises Ltd*
Tel: 0333 3 553 773
Mobile: 07870 667 126
daniel@jowettenterprises.com
www.jowettenterprises.com
