### ISSUE TITLE
I can't transfer ownership

### ISSUE THREAD

**Issue by jpgimenez** [collective/collective.github.com#847]
I'm trying to transfer the ownership of a repository (http://github.com/jpgimenez/collective.localheaderandfooter) to collective but github complains about the lack of permissions and neither I can create the repo inside collective and push.

**Comment by aclark4life** [comment]
OK that's probably because https://help.github.com/articles/transferring-a-repository/#transferring-from-a-user-to-an-organization, working on it!

**Comment by jpgimenez** [comment]
Should I request to join the @collective/transfers team?

**Comment by aclark4life** [comment]
I can add you… but then what happens? I'm still trying to figure it out.

**Comment by jpgimenez** [comment]
I can do some testing from my side if you need it.

**Comment by aclark4life** [comment]
Cool please do

**Comment by ebrehault** [comment]
Not sure it is related, but I cannot add new repositories in collective anymore.
Something changed recently in the access rights?

**Comment by jpgimenez** [comment]
me neither

**Comment by aclark4life** [comment]
@ebrehault Yes, https://github.com/blog/2020-improved-organization-permissions

**Comment by jpgimenez** [comment]
After getting into @collective/transfers I still get "You don’t have admin rights to collective"

**Comment by aclark4life** [comment]
@jpgimenez Can you join #plone.org to discuss?

**Comment by jensens** [comment]
is this related to #850 ?

**Comment by aclark4life** [comment]
@jensens yes

**Comment by jensens** [comment]
Ownership transfers should be enabled again. I fixed #850 mostly.
Please confirm and close this issue.

**Comment by jpgimenez** [comment]
confirmed, is working!
