### ISSUE TITLE
Integrate "improved org permissions" into collective

### ISSUE THREAD

**Issue by aclark4life** [collective/collective.github.com#850]
GitHub has recently announced changes to the way permissions are managed in organizations:

- https://github.com/blog/2020-improved-organization-permissions

If I'm not mistaken this has broken the collective, which means we need to integrate the new features ASAP so folks can add repositories again.

**Comment by keul** [comment]
You are right, I can't add new repos now.

**Comment by jensens** [comment]
I looked at it. it seems - how i understand it - that github now supports exactly what we need using the form here:
https://github.com/organizations/collective/settings/member_privileges

- we want every member to be able to create repositories - this is the team ``CanAdd`` - and it does not work any longer
- we want every member to have write access - this is the team ``--auto-contributors``. Every new repository has ``--auto-contributors`` as team with write access.

If I understand it correctly the ``CanAdd`` team can be removed and instead in above form option ``Allow members to create repositories for this organization`` can be checked.

I'am not sure about the ``--auto-contributors`` - how is it added to each new repository? From what I understand its also no longer needed, because if we set in the second block of the above form ``Default repository permission`` to ``write`` all members will be able to clone, pull, and push all repositories. 

So actions to be done:
- check ``Allow members to create repositories for this organization`` and Save
- remove defect team ``CanAdd``
- under ``Default repository permission`` check radio button ``write``
- remove now superfluos team ``--auto-contributors``
- remove the magic which add the ``--auto-contributors`` to new repositories

Opinions? Corrections?

**Comment by jensens** [comment]
Also learned: ``Owners`` are now a role - I renamed the ``Owners`` team to ``Core``, as suggested by Github. Being part of the Owners (or now Core) team has no effect any more, its just a bunch of people without any special permissions and a mention @collective/core

**Comment by jensens** [comment]
checked together with @agitator (as non-owner) - the above actions are working as expected. So I just need some input about the ``--auto-contributors`` magic. Anybody here from @collective/core has an idea?

**Comment by aclark4life** [comment]
Thanks @jensens for taking the time to look in to this! ``--auto-contributors`` is left over from the early days of the GitHub collective when we used: https://github.com/collective/github-collective. We may still be using some form of this, I think @MatthewWilkes can confirm that. Either that or we turned it off and he wrote something better to do the same thing. In any event, we probably need to turn that off and then make whatever changes you think are appropriate to the teams. (Worst case, just do it and we'll worry about turning the script off later assuming it's not still actively making changes.)

**Comment by jensens** [comment]
I renamed the ``--auto-contributors`` to ``--old--auto-contributors`` - lets see if something fails.

**Comment by jensens** [comment]
further tests together with @agitator are showing, that --auto-contributors are superfluos. I remove the group now.

**Comment by jensens** [comment]
Update: It is not possible to remove it.

**Comment by jensens** [comment]
FYI: Support request sent as follows:

    Dear Github Support Team,

    I tried now several times to delete an now (after you introduced the new "Improved organization permissions") superfluos team of our organisation "collective". 
    The delete button is active at: 
    https://github.com/orgs/collective/teams/old-auto-contributors/edit
    If I click on it I got an alter asking me if "Are you sure you want to delete this team? Once deleted, it can’t be undone.", then I click OK. Now the delete button is inactive. No errors are shown. But the team still exists. Next time I reload the edit-page the button is active again.
    Please tell me how we can delete this organisation. 
    TIA and best regards
    Jens Klein

**Comment by aclark4life** [comment]
Strange they've not removed ``--old-auto-contributors`` by now

**Comment by jensens** [comment]
github.com tech support works on the problem. just let give them some time.
Am 18.08.2015 08:18 schrieb "Alex Clark" <notifications@github.com>:

**Comment by MatthewWilkes** [comment]
Hi all,

@aclark4life is correct, the team was created by https://pypi.python.org/pypi/mr.sisyphus.

It used to be that having add access was signified by membership of a team that had admin rights on repositories, even if that team had no repos. Any repos added would belong to that team.

What mr.sisyphus would do was automatically copy people between the two teams and move repositories out of the CanAdd team into the contributors team. The name is a hold-over from the previous way we did things.

**Comment by MatthewWilkes** [comment]
Also, can I request we use a different name for the 'core' team? The idea is that it's a team that allows people to delete repos, not a status symbol. We've already got people applying to be core developers by requesting to join it.

**Comment by aclark4life** [comment]
@MatthewWilkes Thanks for the feedback! And I renamed Core to Members

**Comment by cbcunc** [comment]
@jensens Thanks for working this out.

**Comment by aclark4life** [comment]
@cbcunc @jensens +1000 :cake:

**Comment by aclark4life** [comment]
@jensens Two questions:

- Do we need to "add people" to the collective any more, like we used to?
- Do you want me to check on @github's progress in removing ``--auto-contributors-old`` ?

**Comment by aclark4life** [comment]
I just realized calling the former-Owners team "Members" makes no sense & is confusing. (Joining the organization makes you a Member.) As such, I've renamed this group to Staff. This is potentially useful if we want to promote our ability to notify all "staff" via @collective/staff syntax (hello all 26 "staff" members! :-)). Otherwise, we may consider removing this group.

**Comment by aclark4life** [comment]
@github @jensens Just tried again and at least got an error this time:

![screenshot 2015-10-01 15 57 23](https://cloud.githubusercontent.com/assets/72164/10232196/493d611e-6855-11e5-96a6-086cc5996795.png)

Maybe the team needs to be removed from all repos before it can be deleted from the org?

**Comment by jensens** [comment]
checked, this is still aproblem

**Comment by jensens** [comment]
old team removed, so we can close this one

**Comment by aclark4life** [comment]
Almost cried tears of joy when I got this:

![screenshot 2016-03-29 07 01 09](https://cloud.githubusercontent.com/assets/72164/14105927/6f28ad48-f57c-11e5-9d3a-cd8d40a7cad1.png)

**Comment by jensens** [comment]
i did nothing special, just tried to hit the button again. :)

**Comment by aclark4life** [comment]
Hah! Crazy
