### ISSUE TITLE
Migrate RadioFreeAsia/Products.CompositePack to Collective

### ISSUE THREAD

**Issue by flipmcf** [collective/collective.github.com#851]
I've done all the SVN work, just 2 steps need completing that I do not have permissions to do:

In this order:

1) Change the owner of https://github.com/RadioFreeAsia/Products.CompositePack to Collective

2) Run the final "move old trunk" step on https://github.com/collective/collective.github.com/blob/master/old-svn.rst

    export PRODUCTNAME="Products.CompositePack"
    cd ..
    svn mv -m "Moved to github" https://svn.plone.org/svn/collective/${PRODUCTNAME}/trunk https://svn.plone.org/svn/collective/${PRODUCTNAME}/trunk.old
    svn mkdir -m "Moved to github" https://svn.plone.org/svn/collective/${PRODUCTNAME}/trunk
    svn co https://svn.plone.org/svn/collective/${PRODUCTNAME}/trunk/ ${PRODUCTNAME}.old
    cd ${PRODUCTNAME}.old 
    echo "Repo moved to https://github.com/collective/${PRODUCTNAME}" > MOVED-TO-GITHUB.txt
    svn add MOVED-TO-GITHUB.txt
    svn commit -m "Added Github moved notice"

**Comment by jensens** [comment]
Transfer of ownership into collective should work now for all collective members again, see also #850

**Comment by flipmcf** [comment]
Thank you.  I transferred ownership and used ALL the teams, just to make sure:  Owners, Core, and --old-auto-contributors.  Although after reading #850 the latter is probably unnecessary.  Just the Owners and Core teams were a bit confusing.
