### ISSUE TITLE
Enable Travis for collective.honeypot

### ISSUE THREAD

**Issue by mauritsvanrees** [collective/collective.github.com#859]
Hi, can anyone enable Travis for https://github.com/collective/collective.honeypot
Thankis.

**Comment by aclark4life** [comment]
Done, do I need to add any credentials?

**Comment by mauritsvanrees** [comment]
Not as far as I know. Seems fine like this. Thanks!

Well, Travis complains about my .travis.yml, although http://lint.travis-ci.org is happy with it, but that is a different problem.
