### ISSUE TITLE
Please enable Travis CI for Products.PloneServicesCenter

### ISSUE THREAD

**Issue by macagua** [collective/collective.github.com#860]

**Comment by aclark4life** [comment]
Done, do I need to add any credentials?

**Comment by macagua** [comment]
@aclark4life thanks!

What kind of credentials?

**Comment by aclark4life** [comment]
No idea, does it work for you now?

**Comment by macagua** [comment]
@aclark4life https://travis-ci.org/collective/Products.PloneServicesCenter/ Done! 

Thanks!
