### ISSUE TITLE
Please add me to the collective

### ISSUE THREAD

**Issue by allcaps** [collective/collective.github.com#864]
I work at Zestsoftware and like to contribute to the collective. Please add me.

Thank you!

**Comment by aclark4life** [comment]
I'm not sure if we still need to do this based on progress made in #850, I fill find out and get back to you.

**Comment by allcaps** [comment]
I am not yet a member, therefore I can not create a branch or push anything to plone.app.locales. For the time being I forked and pushed my work here: https://github.com/allcaps/plone.app.locales/tree/allcaps-nl

What will the new workflow be? Does this mean I have to submit a PR?

**Comment by aclark4life** [comment]
Never mind, invite sent. Welcome!

**Comment by allcaps** [comment]
Cool. Thanks.
