### ISSUE TITLE
Permissions: Can't push anymore?

### ISSUE THREAD

**Issue by ramonski** [collective/collective.github.com#868]
I want to push some changes to https://github.com/collective/plone.jsonapi.routes, but I get the following error:

```
(brk)src/plone.jsonapi.routes [ g push                                                                          plone-jsonapi-routes-0-9 ] 8:59 pm
fatal: remote error:
  You can't push to git://github.com/collective/plone.jsonapi.routes.git
  Use https://github.com/collective/plone.jsonapi.routes.git
```

Did someone change the permissions?

**Comment by aclark4life** [comment]
Could be related to #850 though no one else has complained yet.

**Comment by ramonski** [comment]
Hi Alex

Hmm, other (non collective) repos are working as usual.
It was possible to push to this repo 3 days ago. Any ideas?

**Comment by ramonski** [comment]
Found the problem. Seems to be related to `mr.developer`.

I added this line in my `buildout.cfg`: 

```
[sources]
plone.jsonapi.routes = git git://github.com/collective/plone.jsonapi.routes.git branch=plone-jsonapi-routes-0-8-2
```

Within this repo I get the described problem. Pushing from the non-mr.developer-repo is working...

**Comment by thet** [comment]
@ramonski the git://github.com url scheme doesn't allow pushing, AFAIK. use the git@github.com
you can also use pushurls with mr.developer. like this line:

``plone.jsonapi.routes = git git://github.com/collective/plone.jsonapi.routes.git pushurl=git@github.com:collective/plone.jsonapi.routes.git``

**Comment by ramonski** [comment]
@thet thanks for the hint!
