### ISSUE TITLE
move some repositories from svn collective

### ISSUE THREAD

**Issue by vincentfretin** [collective/collective.github.com#886]
Can somebody be kind enough to migrate the following repositories before the svn become read-only?
https://svn.plone.org/svn/collective/Products.DocFinderTab/trunk
https://svn.plone.org/svn/collective/Products.cooptation/trunk
https://svn.plone.org/svn/collective/Products.projectmanager/trunk
https://svn.plone.org/svn/collective/Products.rendezvous/trunk
https://svn.plone.org/svn/collective/collective.contentrules.comingsoon/trunk
https://svn.plone.org/svn/collective/collective.js.colorpicker/trunk
https://svn.plone.org/svn/collective/collective.rdfadcviewlet/trunk

Thanks

**Comment by aclark4life** [comment]
@vincentfretin I think we have documentation that describes how to do this… somewhere.

**Comment by jensens** [comment]
I fear the above link is outdated, its is easier to use: https://import.github.com/new

**Comment by aclark4life** [comment]
@jensens Wow nice

**Comment by vincentfretin** [comment]
@jensens cool, I'm trying to import https://svn.plone.org/svn/collective/collective.rdfadcviewlet now

**Comment by vincentfretin** [comment]
2% complete in a hour. :)

**Comment by jensens** [comment]
yes, this takes a while. I moved some already in past, sometimes with aborts and need to restart, but finally i got everything imported.

**Comment by vincentfretin** [comment]
collective.rdfadcviewlet is moved. I close the issue. I will take care of moving the remaining packages myself.
