### ISSUE TITLE
Please add me to the collective

### ISSUE THREAD

**Issue by dpopsmg** [collective/collective.github.com#894]
Hi!

Could you please add me to the collective.  My github user name is dpopsmg.  I have a new product or Plone 5 for display of RelationList and RelationChoice Dexterity TTW widgets as an actul list of links rather than Catalog UIDs, and substantial work I would like to commit to the plone 5 branch of Solgema.calendar that has really started getting it working.

Thank you

Matt Grant
matt.grant@foodstuffs-si.co.nz

**Comment by aclark4life** [comment]
Invite sent, welcome!
