### ISSUE TITLE
(Re)activate travis for Products.AutoUserMakerPASPlugin

### ISSUE THREAD

**Issue by tomgross** [collective/collective.github.com#898]
Can someone please (re)activate travis for Products.AutoUserMakerPASPlugin. It somehow got removed or something there. Thanks!
https://travis-ci.org/collective/Products.AutoUserMakerPASPlugin

**Comment by jensens** [comment]
activated on travis - do you need something do be done on github as well?

**Comment by tomgross** [comment]
Seems to work. Thanks @jensens for the lightning fast response!
