### ISSUE TITLE
Please add me to the collective

### ISSUE THREAD

**Issue by volkerjaenisch** [collective/collective.github.com#900]
We, Sandra Rum and Volker Jaenisch, are currently releasing "inqbus.tagging - autotagging for plone" for the collective. Would be nice if you let me in.

Thank you

**Comment by gforcada** [comment]
Hi!

You have been invited.

Welcome to Plone community!

**Comment by volkerjaenisch** [comment]
THank You!

Am 27.01.2016 um 13:20 schrieb Gil Forcada Codinachs:
>
> Hi!
>
> You have been invited.
>
> Welcome to Plone community!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/collective/collective.github.com/issues/900#issuecomment-175590675>.
>

-- 
=========================================================
   inqbus Scientific Computing    Dr.  Volker Jaenisch
   Richard-Strauss-Straße 1       +49(08861) 690 474 0
   86956 Schongau-West            http://www.inqbus.de
=========================================================
