### ISSUE TITLE
New packages configuration (collective.eeafaceted...)

### ISSUE THREAD

**Issue by gbastien** [collective/collective.github.com#909]
Hi,

I just moved 2 packages https://github.com/collective/collective.eeafaceted.collectionwidget and https://github.com/collective/collective.eeafaceted.z3ctable, I forgot to set correct access to "Staff", could someone correct this?

Moreover is it possible to activate Travis for these 2 packages + https://github.com/collective/collective.ckeditortemplates?

Thank you!

Gauthier

**Comment by jensens** [comment]
i don't think we need staff on it, since staff has access to all collective anyway.
under https://travis-ci.org/profile/collective the projects are not yet showing up. maybe travis caches the list for a while and so we need to wait until it is refreshed.

**Comment by gbastien** [comment]
@jensens 

ok thank you, I see Travis is activated now.

Gauthier

**Comment by mauritsvanrees** [comment]
Looks like this can be closed. Please reopen if I'm wrong.
