### ISSUE TITLE
please rename collective.documentfile & enable Travis

### ISSUE THREAD

**Issue by petri** [collective/collective.github.com#927]
I recently transfered [collective.documentfile](https://github.com/collective/collective.documentfile) to collective. 

Please rename the package to **collective.filemeta** and enable Travis CI for it.

Background: Unfortunately I only after the transfer realized that the package feature set and scope should be changed a bit and that the package name will be very much misleading after that.

This package is under early development, not yet released to PyPI nor used anywhere in production. So rename should cause no problems to anyone.

Thanks, and sorry for the trouble.

**Comment by jensens** [comment]
renamed, but it does not yet show up in travis, so I think we need to wait for travis to sync with github to get the renamed repo.

**Comment by jensens** [comment]
Worked now. Travis CI should be activated.
