### ISSUE TITLE
Please add me to the collective

### ISSUE THREAD

**Issue by ZuluPro** [collective/collective.github.com#944]
Hello,
Could you please give me write permissions to this organisation?

Thanks

**Comment by alecghica** [comment]
+1

**Comment by aclark4life** [comment]
Is this a request to join the @collective/staff ?

**Comment by alecghica** [comment]
yes

**Comment by alecghica** [comment]
Can we please have @ZuluPro added to the organisation? he is working with us at Eau de Web doing Plone development.

**Comment by jensens** [comment]
Invite sent

**Comment by alecghica** [comment]
@jensens thx! I'll owe u a beer in Boston :)
